openapi: "3.0.0"
info:
  version: 1.0.1
  title: Swagger Petstore
  license:
    identifier: ""
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - description
        - fields
      properties:
        id:
          type: string
          format: UUID
        title:
          type: string
        description:
          type: string
        disabled_at:
          type: string
          format: date-time
        fields:
          type: array
          items:
            $ref: "#/components/schemas/TaskField"
    TaskFieldValue:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    TaskRecord:
      type: object
      required:
        - id
        - task_id
        - user_id
      properties:
        id:
          type: string
          format: UUID
        task_id:
          type: string
          format: UUID
        # user_id:
        #   type: string
        #   format: UUID
        completed_at:
          type: string
          format: date-time
        field_values:
          type: array
          items:
            $ref: "#/components/schemas/TaskFieldValue"

    TaskField:
      type: object
      properties:
        id:
          type: string
          format: UUID
        name:
          type: string
        description:
          type: string
        is_required:
          type: boolean
        type:
          type: string
          enum:
            - checkbox
            - input
            - number
            - textarea
    Pet:
      type: object
      required:
        - id
        - name
        - birthday
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthday:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
